[package]
name = "regy_bot"
version = "1.3.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serenity = { version = "0.10.10", features = ["framework", "builder"] }
tokio = { version = "1.33.0", features = ["full"] }
regex = "1.10.2"
serde = { version = "1.0.189", features = ["derive"] }
toml = "0.8.4"
base64 = "0.21.5"
uuid = { version = "1.5.0", features = ["v4", "serde"] }
chrono = "0.4.31"
