[package]
name = "regy_bot"
version = "1.8.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
poise = "0.5.5"
tokio = { version = "1.28.0", features = ["full"] }
regex = "1.8.1"
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
base64 = "0.21.0"
uuid = { version = "1.3.2", features = ["v4", "serde"] }
chrono = "0.4.24"
