[package]
name = "regy_bot"
version = "1.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
poise = "0.5.2"
tokio = { version = "1.25.9", features = ["full"] }
regex = "1.7.3"
serde = { version = "1.0.158", features = ["derive"] }
toml = "0.7.3"
base64 = "0.21.0"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
chrono = "0.4.24"
