[package]
name = "regy_bot"
version = "1.9.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
poise = "0.5.5"
tokio = { version = "1.28.1", features = ["full"] }
regex = "1.8.1"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.3"
base64 = "0.21.0"
uuid = { version = "1.3.3", features = ["v4", "serde"] }
chrono = "0.4.24"
self-replace = "1.3.1"

[[bin]]
name = "regy_bot"
path = "src/main.rs"

[[bin]]
name = "regy_bot_update_helper"
path = "src/update_helper.rs"