[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serenity = { version = "0.10", features = ["framework"] }
tokio = { version = "1.25.0", features = ["full"] }
regex = "1.5.4"
serde = { version = "1.0.158", features = ["derive"] }
toml = "0.5.8"