[package]
name = "regy_bot"
version = "1.3.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serenity = { version = "0.10.10", features = ["framework", "builder"] }
tokio = { version = "1.29.1", features = ["full"] }
regex = "1.9.1"
serde = { version = "1.0.176", features = ["derive"] }
toml = "0.7.6"
base64 = "0.21.2"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
chrono = "0.4.26"
