[package]
name = "regy_bot"
version = "1.16.0"
edition = "2021"

[dependencies]
poise = "0.5.7"
tokio = { version = "1.33.0", features = ["full"] }
regex = "1.10.2"
serde = { version = "1.0.189", features = ["derive"] }
toml  = { version = "0.8.4", optional = true }
base64 = "0.21.5"
uuid = { version = "1.5.0", features = ["v4", "serde", "fast-rng"] }
self-replace = "1.3.7"
owo-colors = "3.5.0"
scorched = "0.3.0"
ron = "0.8.1"
reqwest = { version = "0.11.22", features = ["blocking"] }
fuzzy-matcher = "0.3.7"
rand = "0.8.5"

[[bin]]
name = "regy_bot"
path = "src/main.rs"

[features]
toml-updating = ["toml"]
developer-commands = []
test-deploy = []
legacy-staff = []

default = ["developer-commands", "legacy-staff"]

[[bin]]
name = "regy_bot_update_helper"
path = "src/update_helper.rs"
