[package]
name = "regy_bot"
version = "1.14.9"
edition = "2021"

[dependencies]
poise = "0.5.6"
tokio = { version = "1.32.0", features = ["full"] }
regex = "1.9.6"
serde = { version = "1.0.188", features = ["derive"] }
toml  = { version = "0.8.2", optional = true }
base64 = "0.21.4"
uuid = { version = "1.4.1", features = ["v4", "serde", "fast-rng"] }
self-replace = "1.3.7"
owo-colors = "3.5.0"
scorched = "0.2.4"
ron = "0.8.1"
reqwest = { version = "0.11.22", features = ["blocking"] }
fuzzy-matcher = "0.3.7"
rand = "0.8.5"

[[bin]]
name = "regy_bot"
path = "src/main.rs"

[features]
toml-updating = ["toml"]
developer-commands = []
test-deploy = []

default = ["developer-commands"]

[[bin]]
name = "regy_bot_update_helper"
path = "src/update_helper.rs"
