[package]
name = "regy_bot"
version = "1.12.9"
edition = "2021"

[dependencies]
poise = "0.5.5"
tokio = { version = "1.28.2", features = ["full"] }
regex = "1.8.4"
serde = { version = "1.0.171", features = ["derive"] }
toml = "0.7.5"
base64 = "0.21.2"
uuid = { version = "1.4.0", features = ["v4", "serde"] }
self-replace = "1.3.5"
owo-colors = "3.5.0"
scorched = "0.2.3"
once_cell = "1.18.0"

[[bin]]
name = "regy_bot"
path = "src/main.rs"

[[bin]]
name = "regy_bot_update_helper"
path = "src/update_helper.rs"
