[package]
name = "regy_bot"
version = "1.14.0"
edition = "2021"

[dependencies]
poise = "0.5.5"
tokio = { version = "1.32.0", features = ["full"] }
regex = "1.9.4"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.8.1"
base64 = "0.21.3"
uuid = { version = "1.4.1", features = ["v4", "serde", "fast-rng"] }
self-replace = "1.3.6"
owo-colors = "3.5.0"
scorched = "0.2.4"
ron = "0.8.1"
reqwest = { version = "0.11.20", features = ["blocking"] }
fuzzy-matcher = "0.3.7"

[[bin]]
name = "regy_bot"
path = "src/main.rs"

[[bin]]
name = "regy_bot_update_helper"
path = "src/update_helper.rs"
