name: Auto Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/auto-build.yml'

  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/auto-build.yml'

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: CreateRelease
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            target/release/regy/regy_bot.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          releaseName: ${{ github.ref }}
          releaseNotes: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false